### ISSUE TITLE
Synchronous navigation of tracks seems broken

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling.js#1043]
I found the issue in the GIVE example on the Editor (https://gosling.js.org/?example=GIVE) and also in the Gosling Designer that uses the most recent Gosling version.

I can reproduce this by zooming in (e.g., seeing a few hundred BPs), panning, and then zooming out quickly.

https://github.com/gosling-lang/gosling.js/assets/9922882/5785e7fd-9dc4-4a0c-9b41-59390c593340

I see the following error message:

![Screenshot 2024-02-22 at 8 55 24 AM](https://github.com/gosling-lang/gosling.js/assets/9922882/b50d0ec7-6802-412c-b40a-cf6c70b72eb7)

Copied texts:
```
index-fdb53256.js:1668 Uncaught RangeError: Maximum call stack size exceeded
    at new MJt (index-fdb53256.js:1668:1241331)
    at index-fdb53256.js:1668:1264625
    at Array.forEach (<anonymous>)
    at _e.transformDataAndCreateModels (index-fdb53256.js:1668:1263708)
    at index-fdb53256.js:1668:1259473
    at Array.flatMap (<anonymous>)
    at _e.processAllTiles (index-fdb53256.js:1668:1259456)
    at Ie (index-fdb53256.js:1668:1256496)
    at _e.draw (index-fdb53256.js:1668:1256723)
    at _e.zoomed (index-fdb53256.js:1668:1258755)
```

The maximum call stack error is coming from the following code:

https://github.com/gosling-lang/gosling.js/blob/9ecd4d30d1ae01a7ceb4edf4effe85a3eed2b619/src/tracks/gosling-track/gosling-track-model.ts#L82

**Comment by etowahadams** [comment]
Interesting! That line was added in [this PR](https://github.com/gosling-lang/gosling.js/pull/988/files#diff-a493851e3aeae402d10f69be75284df4eca5377e82ed364bdcad97abeb8ef1deR82). I'll look into this.
