### ISSUE TITLE
Use more understandable units for `zoomLevel` in `visibility`

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling.js#154]

**Comment by sehilyi** [comment]
@wangqianwen0418 Before I forget, I will update the `zoomLevel` part in the docs, but I thought you might need to know this update.

I've changed the unit of `zoomlevel` to a more understandable one, base pair (bp). For example, `zoomLevel === 100` means you are seeing 100 base pairs (e.g., chr1:1 ~ chr1:100) in the track by the current zoom level. Also, I've changed to allow using `zoomLevel` with `target: 'mark'` and `transitionPadding`, so smooth transition is supported with `zoomLevel`, FYI.

**Comment by wangqianwen0418** [comment]
Sounds great! 
Many thanks~
