### ISSUE TITLE
Getting started tutorial

### ISSUE THREAD

**Issue by wangqianwen0418** [gosling-lang/gosling.js#156]
:note:

- use simple csv data to create basic visualizations
- go through all basic elements in Gosling Grammar

**Comment by sehilyi** [comment]
I think semantic zooming might be good example in the tutorial as well.

**Comment by wangqianwen0418** [comment]
@sehilyi , I would like to ask you a favor:

- Would you mind creating a CSV example that can be used for different visualizations? 
- Can you transfer the previous Geminid-react to Gosling?

**Comment by sehilyi** [comment]
@wangqianwen0418 Yes, I will work on the second one now. For the first one, I guess it would be best if it contains genomic information rather than genera information?

**Comment by wangqianwen0418** [comment]
> For the first one, I guess it would be best if it contains genomic information rather than genera information?

Yes!

**Comment by sehilyi** [comment]
@wangqianwen0418 I've updated the `README.md` file and also code to use Gosling.js in Gosling-React repo (https://github.com/gosling-lang/gosling-react).

**Comment by wangqianwen0418** [comment]
Many thanks!

**Comment by sehilyi** [comment]
This is a small dataset I found at the Circos website (three categorical columns, one quantitative column): [demo](<https://gosling-lang.github.io/gosling.js/?full=false&spec=(5'ZtleDBasic%20MRks'GsubZtleDTutorial%20Examples'GlayoutDlineR'GRrangem_tO'direcZonDverZcal'7row~1807column~800)Gtracks4%5B5*(C'dataX'urlDhttps%3A%2F%2Fraw.githubusercont_t.cjLlangLdataset%2Fmain%2Fcircos%2Fboth.cons.2e6.merged.avg.txtAcsv'NPFVDchr'NIFVs4%5B'stRt'7_d'%5DNsepRatorDUCJmRkDbR'3'xX9stRtAI'NdjainO'PD1')NaxisDtop'CJxeX9_dAI'CJyX9HAKCJrowO9category'7Qnjinal'7leg_d4trueYOUHDwhite'YWidthO'H40.1JcolorO9H'7QK)5*)5%5D%0A)*%20%203%2CC4!%205%0A*7%2CU9'fVDA'NQC5**D4'G%2C5'HvalueIg_jicJ)3'KquanZtaZve'L%2Fgosling-N3*'O4(PchrjosjeQtypeDRarU%20'VieldXOC*YJstrokeZti_enjom~Sizes4%01~j_ZYXVURQPONLKJIHGDCA97543*_>)

You can also use [cytoband example](<https://gosling-lang.github.io/gosling.js/?full=false&spec=(%0A*'layoutK'linear'%2C%0A*'arrangementK('directionK'verticalLcolumnSizesK800%3FrowSizesK60)%2C%0A*'tracks%7B%0A**(V'dataK(J'urlK'https%3A%2F%2Fraw.githubusercontent.com%2Fsehilyi%2Fgemini-datasets%2Fmaster%2Fdata%2FUCSC.HG38.Human.CytoBandIdeogram.csv'M'%3Ccsv'M'c%3DFieldK'C%3D'M'%40Fields%7B'%7DLchromEnd'%5DV%26uperpose%7BJ(J*'markK'text'MRQ%3BtextK(XNameL%5E)M*'colorK(J%22MY~'%3EL%3EL%3EL%3ELwhiteL%3E'jvisibility%7BJ**(J***'operationK'less-thanZmeasureK'widthZthresholdK'%7Cxe-x%7CZtransitionPaddingK10M***'targetK'mark'J**)J*%5DM*'styleK('textS%7FK0%24rect'MRQ%3BcolorK(J%22MY~J***'whiteZ%23D9D9D9Z%23979797Z%23636363Z%3EZ%23A0A0F2'J**%5DJ*%60-r'MRJ***Q%25q')J**j%2B%60-l'MRJ***Q%25p')J**j%2B)J)V%5D%2CV'xK(JX%7D'M'%3C%40'M'domainK('c%3DK'1')M'axisK'top'V)%2CV'xeK(XchromEndL%3C%40'%26ize_20%26troke_'gray'%26%7F_0.5%26tyleK('outlineK'white')%0A**)%0A*%5D%0A)*%20%20JV*K!%20L'%3FM%2CJQ(XStainLoneOf%7B'acen'%5DR*'dataTransformK(J**'filter%7BV%0A***X'fieldK'Y**'domain%7B'gnegLgpos25Lgpos50Lgpos75Z'M***'_K('valueKj%5DJ*)M*'~Lgpos100Lgvar'%5DM**'range%7B%22**XStain'M**'%5E%24)J)M(J*'markK'%25)M***(XNameLincludeK'%26)%2CV's%2Bcolor_'%23B40101'%3B%3FnotKtrue)j%3CtypeK'%3Dhromosome%3Eblack%3F%2C%20'%40genomic%5E%3Cnominal'%60%24triangle%7BK%5B%7DchromStart%7FtrokeWidth%01%7F%7D%7B%60%5E%40%3F%3E%3D%3C%3B%2B%26%25%24%22~j_ZYXVRQMLKJ*_>) and [arc example](<https://gosling-lang.github.io/gosling.js/?full=false&spec=(A'layout~ear'N'arrangementKAOdirectionHvertical'NOcolumnSizes5800NOrowGapsM30B0%5DA)N'tracksMA*(4'PK4OurlHhttps%3A%2F%2Fraw.githubusercontent.cW%2Fsehilyi%2Fgemini-Psets%2Fmaster%2FP%2Fcircos-segdup-edited.txt'6OYcsv'6*IFQHc2'6ORFQsM's1qe1qs2qe2'%5D4_superposeMZ(ZOmark~k'jU1V9JeKDe1X7)j1U2V9J1eKDe2X7)Z)4%5D6'colorCstrokeCopacityT50.1_styleK'circularLink5true)A*)A%5D%0A)*%20%204A**5!%206%2C47'YR'9'dWainKIH1')EOaxisHA%0A*B%2C%20CTHsteelblue'_D'fQHE6**H5'I'chrWosWeJtop'Z*)jK5(M5%5BN%2CAO*'PdataQieldRgenWicTK'valueUKZ**DsV'E*7E*WomqBYtypeHZ4*_)6'jE'xqX'~Hlin%01~qj_ZYXWVUTRQPONMKJIHEDCBA97654*_>) together with the aforementioned example.

Do these look good to you?
