### ISSUE TITLE
Weak linking between tracks with lollipop (diagonal band/line) representation

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling.js#166]
![Screen Shot 2020-08-28 at 4 53 21 PM](https://user-images.githubusercontent.com/9922882/106654529-3c706300-6566-11eb-894e-a25110f92526.png)
![image](https://user-images.githubusercontent.com/9922882/106654324-00d59900-6566-11eb-975d-52fea196346c.png)
![image](https://user-images.githubusercontent.com/9922882/106654462-26fb3900-6566-11eb-9ed0-19e5c31c05dd.png)
![image](https://user-images.githubusercontent.com/9922882/106654486-2b275680-6566-11eb-90f9-1398fbf46d72.png)

**Comment by ngehlenborg** [comment]
![](http://circos.ca/img/masthead/nyt-epi-02.png)

From the Circos website.

**Comment by sehilyi** [comment]
Closing this since this is supported by #320. But we can further improve algorithms and/or visual representations.
