### ISSUE TITLE
Editor crashes sometimes

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling.js#171]
> If does not contain sufficient information, do not have to go the through rendering process.
![Screen Shot 2021-02-02 at 7 15 17 PM](https://user-images.githubusercontent.com/9922882/106679633-1c06cf80-658b-11eb-9b0f-709341afc075.png)

This issue (using non-color str) is fixed by #211

**Comment by sehilyi** [comment]
Putting random domain name makes the app crashes as well.

![Screen Shot 2021-02-04 at 2 35 00 PM](https://user-images.githubusercontent.com/9922882/106945742-2f827980-66f6-11eb-9b66-c8fed3782c0e.png)

**Comment by sehilyi** [comment]
> { color: {value: 'randomstr'}} seems to also crash the editor

This is fixed by #211

**Comment by wangqianwen0418** [comment]
When removing the `overlay` attribute in "Cyto Bands" example, the online editor crashed

**Comment by sehilyi** [comment]
I think this issue has been addressed by (1) compiling a spec only when it meets the rules defined in `gosling.schema.json` and (2) showing a backup panel with informative messages.
