### ISSUE TITLE
Submit Gosling to aggregator sites

### ISSUE THREAD

**Issue by ngehlenborg** [gosling-lang/gosling.js#254]
- [x] GenoCAT
- [x] https://github.com/cmdcolin/awesome-genome-visualization
    - [x] https://cmdcolin.github.io/awesome-genome-visualization/
- [x] https://github.com/keller-mark/awesome-biological-visualizations

**Comment by flekschas** [comment]
I can also add it to http://bivi.co

**Comment by sehilyi** [comment]
- https://github.com/keller-mark/awesome-biological-visualizations/pull/4
- https://github.com/cmdcolin/awesome-genome-visualization/pull/15 (https://cmdcolin.github.io/awesome-genome-visualization/)
- https://github.com/hms-dbmi/genocat/pull/28

**Comment by sehilyi** [comment]
I added gosling.js to the three aggregator sites.

@flekschas, if you already have an account for http://bivi.co and could add gosling.js to it, that would be helpful as well!
