### ISSUE TITLE
Zooming to very high resolution in the ClinVar example causes browser to freeze

### ISSUE THREAD

**Issue by ngehlenborg** [gosling-lang/gosling.js#255]
I observed this with both Safari and Chrome. Profiler (Chrome) screenshot is attached. The browser does recover eventually and will allow me to zoom out again.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1216518/108849582-4ce98b80-75b0-11eb-81da-e3ab361ca78b.png">

**Comment by sehilyi** [comment]
Using line pattern (i.e., `"style": {"linePattern": {"type": "triangle-r", "size": 5}}`) looks to make the issue.
