### ISSUE TITLE
Allow loading view specs via gist.github.com for deep linking

### ISSUE THREAD

**Issue by flekschas** [gosling-lang/gosling.js#262]
It'd be great to be able to load view specs via gist.github.com to provide a simple solution for linking to custom views that are longer than what can be encoded in the URL.

I'm thinking, in the end the URLs could looks like https://gosling.js.org/flekschas/81e7fb4f9cf5946f12639c383af97dc6 to reference data hosted at https://gist.githubusercontent.com/flekschas/81e7fb4f9cf5946f12639c383af97dc6/. (Ignore the details of the gist, it's just for demonstration).

Loading wise this should be trivial. The only thing we have to specify are the file names. Thinking a bit into the future, it'd be cool if we could load two types:
1. The specification: `gosling.json` or `gosling.js` (I would scan for `.js` to allow loading specs with comments)
2. A readme for an accompanying textual description of the visualization: `README.md`

I am happy to give it a shot as I've implemented this for another tool recently. I would just need some anchor points where this code could go best.

**Comment by sehilyi** [comment]
Thank you for the suggestion, this will be really cool!

These are some related parts of the source code:
**Parsing the spec contained in the url**:
https://github.com/gosling-lang/gosling.js/blob/dddeb2bbd4223d42f7b0e741eb00dc71eb09c3b3/src/editor/editor.tsx#L90

**Initialization part that stores the parsed spec to a state, `code`**:
https://github.com/gosling-lang/gosling.js/blob/dddeb2bbd4223d42f7b0e741eb00dc71eb09c3b3/src/editor/editor.tsx#L97

**Comment by sehilyi** [comment]
Closing this since I think this is addressed by #263.
