### ISSUE TITLE
make landing pages mobile friendly

### ISSUE THREAD

**Issue by ngehlenborg** [gosling-lang/gosling.js#268]
Many people will come to gosling.js.org from mobile devices and currently the homepage is not mobile compatible. I don't want to make Gosling fully mobile compatible at the moment, but there are a few things that we need to do to avoid frustration.

**Major issue 1: README hiding view**

Coming from gist, the README is not closable.

Probably not hard to fix but we need to do this to avoid disappointment, in particular if we use tweets with embedded gist-based examples.

![IMG_2473](https://user-images.githubusercontent.com/1216518/109424859-adfbcf80-79b3-11eb-8f68-fa992e72dbe0.PNG)

**Minor issue 2: Interactions**

I couldn't figure how to zoom out in HiGlass on iOS devices. I can zoom in (double-tap) and pan, but pinching doesn't seem to work (I  shows me the other open browser tabs in Safari on iOS).

**Minor issue 3: Views are tiny**

The editor gets in the way when viewing the visualizations on mobile, is there a way to close it by default on mobile devices?

**Comment by flekschas** [comment]
The gist readme issue might be because I set a min-width. Should be a quick fix. The bigger issue is whether `<SplitPane />` supports responsive layouts, i.e., ideally the width of any pane is never larger than the screen width and if the screen width is too small panes get vertically stacked.

**Comment by ngehlenborg** [comment]
@sehilyi I think with #288 and #289 in place we can close this issue.
