### ISSUE TITLE
Support headerless CSV files

### ISSUE THREAD

**Issue by flekschas** [gosling-lang/gosling.js#282]
I noticed that CSV files currently must have a header to be parsable by Gosling. I think it would be nice to allow users to work with headerless CSV files as well.

I believe the only change needed is to allow specifying the data type of columns via their index. E.g.: `genomicField: 0`.

Related to this we might have to think about a parameter called `hasHeader`, which could be set to `true` by default.

**Comment by sehilyi** [comment]
I think this is not properly included in the docs, but gosling currently supports an optional prop `headerNames: string[]` which is used to let users specify header names by themselves if the CSV file is headerless (e.g., `headerNames: ["chr", "start", "end"]`).

**Comment by sehilyi** [comment]
I will close this issue since we support headerless CSV files. But feel free to reopen this if related issues still need to be addressed.
