### ISSUE TITLE
split examples

### ISSUE THREAD

**Issue by wangqianwen0418** [gosling-lang/gosling.js#368]
@sehilyi , what do you think about splitting some current examples (e.g., semantic zoom) into several small examples.
Some examples are quite dense and may not friendly for new users.

**Comment by sehilyi** [comment]
Sounds good. I think two current examples (i.e., semantic zoom and mark displacement) are the ones that we can split?

**Comment by wangqianwen0418** [comment]
Yes. 
I am also thinking about splitting these basic examples, and access them separately in the example page:
https://gosling-lang.github.io/gosling-website/examples/
We may assume people who check basic examples are beginners and don't prefer long codes?

I have created a pull request to access examples through url. It would be great if you can review it.

Also, feel free to add more examples to the static website (it is at /assets/example-list.js).

**Comment by sehilyi** [comment]
Thank you @wangqianwen0418, they look great! I will add more examples.
