### ISSUE TITLE
add `exportCanvas` to `GoslingComponent`

### ISSUE THREAD

**Issue by manzt** [gosling-lang/gosling.js#449]
The `GoslingComponent` takes an optional `ref` that exposes a public API. The `exportPNG` and `exportPDF` functions are good, but ultimately prompt the end-user.

Is there a way to expose a `exportCanvas` or `renderCanvas` function to this API that hooks into the PIXI renderer? Ultimately I'd like to embed a static rendering of a gosling visualization in a jupyter notebook for offline use.

**Comment by sehilyi** [comment]
Thank you for the issue. It looks to be useful for multiple cases.

I think I can add a simple API to provide `HTMLCanvasElement` that displays static gosling visualization:

```
const canvas = gos.ref.getCanvas(); // HTMLCanvasElement
```

**Comment by sehilyi** [comment]
This has been released in [v0.9.0](https://www.npmjs.com/package/gosling.js/v/0.9.0)
