### ISSUE TITLE
how can tracks be aligned horizontally?

### ISSUE THREAD

**Issue by zhangzhen** [gosling-lang/gosling.js#502]
If tracks can be aligned horizontally, it will be very helpful, because tracks can share the same data but views cannot.

**Comment by sehilyi** [comment]
Tracks cannot be juxtaposed horizontally, and you will need to use views instead. I assume you are wondering this for the workaround explained in https://github.com/gosling-lang/gosling.js/issues/492#issuecomment-917532474?
