### ISSUE TITLE
how can one draw a vertical line?

### ISSUE THREAD

**Issue by zhangzhen** [gosling-lang/gosling.js#509]
I used the mark rule to draw a vertical line, but the line wasn't shown.
```
{
  "data": { ... },
  "mark": "rule",
  "x": {
    "field": "new_end",
    "type": "genomic"
  }
}

```

**Comment by sehilyi** [comment]
Hi Zhen!

I am unsure what specific plot you want to make, but if you want to use the x-axis as a genomic axis (as you suggested in the spec) and draw a vertically long rectangle for given genomic location, than you can use `rect` or `bar` mark:

**Spec**
```js
{
  "views": [
    {
      "tracks": [
        {
          "data": {
            "url": "https://raw.githubusercontent.com/sehilyi/gemini-datasets/master/data/cytogenetic_band.csv",
            "type": "csv",
            "chromosomeField": "Chr.",
            "genomicFields": [
              "ISCN_start",
              "ISCN_stop",
              "Basepair_start",
              "Basepair_stop"
            ],
            "quantitativeFields": ["Band", "Density"]
          },
          "mark": "rect",
          "dataTransform": [
            { "type": "filter", "field": "Density", "include": "10", "not": true }
          ],
          "x": {"field": "Basepair_start", "type": "genomic"},
          "stroke": {"value": "white"},
          "strokeWidth": {"value": 0},
          "width": 500,
          "height": 100
        }
      ]
    }
  ]
}
```

**Screenshot**
![gosling-visualization (45)](https://user-images.githubusercontent.com/9922882/133698913-c829bade-fcf5-4075-8e08-3ad444590eb5.png)

**Comment by sehilyi** [comment]
Closing this since my reply seems to answer the question (see alternating bg colors in a screenshot at https://github.com/gosling-lang/gosling.js/issues/492#issuecomment-921433055).
