### ISSUE TITLE
how can one specify the limits of zoom-in and zoom-out actions?

### ISSUE THREAD

**Issue by zhangzhen** [gosling-lang/gosling.js#513]
After zoom-in actions reach a limit, the plot cannot be zoomed in anymore. The same goes for zoom-out actions. How can I achieve this in Gosling?

**Comment by sehilyi** [comment]
This is not supported at the moment, but we can add a `zoomLimits: [number | null, number | null]` property in the view level:

```js
views: [
   { ...,
      zoomLimits: [1, 1000] // 1bp to 1Kbp resolution
   },
   { ...,
      zoomLimits: [1, null] // 1bp to infinite
   }
]
```

Does this work in your case?

**Comment by zhangzhen** [comment]
> Does this work in your case?

Yes, that's what I want.

@sehilyi I want to make this requirement more clear. The detail view for a gene, e.g. BRCA1 cannot be zoomed-out, but can be zoomed-in up to the limit level as I specified.

**Comment by sehilyi** [comment]
Hi @zhangzhen, https://github.com/gosling-lang/gosling.js/pull/521 implemented this and can be tested in the online editor now (please see the example in the PR).

This will be available in the next release.

**Comment by ManavalanG** [comment]
Hi @sehilyi ! Is it possible to restrict zoom actions at the chromosome level? For example, in this [ideogram example](https://gosling.js.org/?example=doc_rect), I would like to show only the `chr1` and disable the ability to zoom-out/pan to the other chromosomes.
