### ISSUE TITLE
how can one disable data sampling?

### ISSUE THREAD

**Issue by zhangzhen** [gosling-lang/gosling.js#514]
By default, Gosling fetches maximal 1000 records when loading data from an url. Sometimes I want to fetch all the data without sampling, how can I achieve this?
BTW, can local files be loaded also via the "data" property? What is the current working directory for local data fetching?

**Comment by sehilyi** [comment]
You can set `data.sampleLength` with a sufficiently large number:

```js
"data": {
        "url": "https://raw.githubusercontent.com/vigsterkr/circos/master/data/5/segdup.txt",
        "type": "csv",
        "headerNames": ["id", "chr", "p1", "p2"],
        "chromosomePrefix": "hs",
        "chromosomeField": "chr",
        "genomicFields": ["p1", "p2"],
        "separator": " ",
        "longToWideId": "id",
        "sampleLength": 100000 // <--
},
```
