### ISSUE TITLE
Axis w/o "chr"?

### ISSUE THREAD

**Issue by tshauck** [gosling-lang/gosling.js#523]
Hi,

I'm playing around with using gosling to display information w/o a chromosome (a random contig and annotations), and was wondering if it's possible to remove the "chrN: " from the axis? e.g.

![image](https://user-images.githubusercontent.com/421839/134577353-a0510bca-e350-465f-b4f3-00b3310890d8.png)

Thanks!

**Comment by sehilyi** [comment]
Hi Hauck!

Customizing the format of axis labels is not supported at the moment, but this might be relatively easy to implement. 

In your case, do you want to display the cumulative positions as numbers (e.g., `248,956,522` instead of `chr2:100`)?

**Comment by tshauck** [comment]
I think that would work, though for my use case don't foresee needing to span a chromosome in the first place. Here's an image that is roughly what I was trying to recreate...

![image](https://user-images.githubusercontent.com/421839/134777201-ec18886d-30e6-4264-be6a-a1d9b2286042.png)

**Comment by sehilyi** [comment]
If you were to make the figure like it, you could also consider hiding the axis at all (i.e., `x: {..., axis: 'none'}`) since I do not see any axis in the figure.

**Comment by tshauck** [comment]
Thanks, yeah, I guess I don't want to recreate it verbatim. There's also cases where I want just the one contig and its annotations where having the axis labels are still helpful.

I think being able to just remove the "chr" via "none" would work well for me.

**Comment by sehilyi** [comment]
Closing this since this has been supported in the latest release!

**Comment by tshauck** [comment]
@sehilyi Thanks!
