### ISSUE TITLE
Ask for a suggestion about how to draw a plot with nominal data on the x-axis and quantitative data on the y-axis

### ISSUE THREAD

**Issue by zhangzhen** [gosling-lang/gosling.js#529]
As far as I know, genomic data has to be on the x-axis. Correct me if I'm wrong. I need to draw a kind of CNV plot: exon ids are on the x-axis, and the mean of CNs in each exon on the y-axis. Every exon is assigned to the same width in the plot. Should I resort to vega-lite or drawing with React + D3 + PixiJS by myself?

Thanks a lot!
Zhen

**Comment by sehilyi** [comment]
Hi Zhen, 

Gosling.js does not support tracks with no genomic axis. You would need to either manipulate data (e.g., exon ids are represented as numbers, like `[{ exonId: 1, meanCN: 0.4 }, { exonId: 2, meanCN: 1.2 }, ...]`), or use other visualization libraries like you suggested.

**Comment by zhangzhen** [comment]
> You would need to either manipulate data (e.g., exon ids are represented as numbers, like `[{ exonId: 1, meanCN: 0.4 }, { exonId: 2, meanCN: 1.2 }, ...]`)

Is there no need to add the chromosome field? I think that the chromosome field should be also added.

**Comment by sehilyi** [comment]
You could use `unknown` assembly (i.e., `{..., "assembly": "unknown" }`) like in the "SARS-CoV-2" example (in the editor) which does not require `chromosomeField` in the `csv` file.
