### ISSUE TITLE
how can a track be shown/hidden?

### ISSUE THREAD

**Issue by zhangzhen** [gosling-lang/gosling.js#548]
@sehilyi  I want to use a toggle to control if a track is shown or hidden. But I cannot find a property, something like "hidden": true, in the gosling schema for that purpose. Could you please find me out?

Zhen

**Comment by sehilyi** [comment]
The Gosling grammar does not have any property that determines the visibility of a track, something similar to `visibility` in CSS.

I assume you can achieve this by removing/adding a track specification from the spec. Or do you have any other use cases in mind?

**Comment by zhangzhen** [comment]
> I assume you can achieve this by removing/adding a track specification from the spec.

Does this cause any performance issue?

> Or do you have any other use cases in mind?

No, I don't have any at this moment.

**Comment by sehilyi** [comment]
If the track you show does not contain very large data, I think it should work. But, let me know if you confront any issues with this approach.

**Comment by sehilyi** [comment]
Closing this, but feel free to ask further.
