### ISSUE TITLE
how to use latest commit of gosling.js instead of v0.9.8

### ISSUE THREAD

**Issue by zhangzhen** [gosling-lang/gosling.js#560]
I made the following changes to package.json:
"gosling.js": "gosling-lang/gosling.js", and then ran yarn to install the latest gosling.js. But starting my app failed because gosling.js cannot be resolved. I found there is no dist sub-folder in node_modules/gosling.js. I ran npm run build in the folder, ending up getting the error message: "run-p command not found".
How can I use the latest commit on my local machine?

Zhen

**Comment by sehilyi** [comment]
Hi Zhang,

To test an unreleased local version of the gosling.js package, you can use [yarn link](https://classic.yarnpkg.com/en/docs/cli/link):

```sh
# Build gosling.js package
cd gosling.js
yarn build

# Link local version of gosling.js
yarn link

# Use local gosling.js in your project
cd /to/your/project
yarn link gosling.js
```

In this way, your project will refer to the local version of gosling.js.

If you want to use the official version again, 

```sh
# unlink local gosling.js from your project
cd /to/your/project
yarn unlink gosling.js

# reinstall your packages
yarn install
```
