### ISSUE TITLE
Grammars about the responsive design

### ISSUE THREAD

**Issue by wangqianwen0418** [gosling-lang/gosling.js#664]
@sehilyi, I am planning to update docs about the responsive design.
Going through the responsive examples, I have some thoughts and questions and would like to hear your opinions.

- I am wondering whether we can specify the conditions using a more unified expression, e.g., something like [`alt.condtion` in altair](https://altair-viz.github.io/user_guide/generated/api/altair.condition.html#altair.condition). Instead of specifying a spec at two different places, 
``` 
      "layout": "circular",
      "responsiveSpec": [
        {
          "spec": {"layout": "linear"},
          "selectivity": [
            {"measure": "aspectRatio", "operation": "GT", "threshold": 1.5}
          ]
        }
      ],
```
maybe we can use something like
(assuming now the `type layout = string|condition`)
```
  "layout": {
    "ifTrue": "linear", 
    "ifFalse": "circular",
    "condition":  {"measure": "aspectRatio", "operation": "GT", "threshold": 1.5}
  }
```

- the same goes for the `responsiveSize`.
instead of specifying it at two places
```
"responsiveSize": {"width": true},
 "width": 400,
```
do you think it will be more convenient to write the below?
```
"width": {
  "ifTrue": 400,
  "ifFalse": "vw", // not sure what is the best way to express the screen size here
  "condition": {"measure": "width", "operation": "GT", "threshold": 1000}
}
```
or just ` "width": "vw"` if the width is always the width of the screen.

This definition is also consistent with the type definition of the `visibility` object, by considering the default value as `"ifTrue": "visible", "ifFalse": "invisible"`.

-  In a `circular` layout, the height of a track has no meaning in terms of the number of pixels. Will it be confusing if a user wants a circular chart to respond to the change of (screen) height? What is the proper way to define that?

**Comment by sehilyi** [comment]
@wangqianwen0418 Thanks a lot for sharing your thoughts! 

I used the current approach over others considering several aspects, but it might not be the optimal one, and having this kind of discussion is helpful.

I think one of the main advantages of the current approach is that alternative specs are defined in a **condition-centric way**, i.e., you can collectively see alternative specs within each device condition you define. For example, changing only the `layout` is a simple case, but multiple properties can be changed (e.g., `layout`, `arrangement`, `views`, `tracks`), which might be a more common case. In this case, a specific device `condition` can be defined only once and all corresponding properties can be defined in a single place:

```js
"layout": "circular",
"responsiveSpec": [{
    "selectivity": [ /* condition that determines a smartphone device */ ],
    "spec": {
      "layout": "linear",
      "arrangement": "horizontal", // replace the default "vertical" arrangement
      "tracks": [ /* alternative tracks */ ]
    }
}]
```

This condition-centric syntax is similar to CSS-based responsive design (This does not mean CSS is the optimal one, but I wanted to make our grammar for the responsive design not too new to people):
```css
@media screen and (/* condition that determines a smartphone device */) {
    view-1 {
       /* change multiple properties here */
    }
}
```

Another worth-mentioning aspect is that one can define multiple conditions (e.g., smartphone, tablet, and PC). Not sure if Altair's `condition` allows defining multiple conditions, but in the **property-centric way**, users will need to define these conditions redundantly for individual properties. This means that if a user wants to make a slight change on one of the conditions, s/he will need to change it in multiple places (this is related to _viscosity_ often referred to when designing visualization grammars).

Let me know if you think this makes sense to you.

**Comment by sehilyi** [comment]
> In a circular layout, the height of a track has no meaning in terms of the number of pixels. Will it be confusing if a user wants a circular chart to respond to the change of (screen) height? What is the proper way to define that?

Ah, yes! I think I really need to address our previous GitHub issue on this problem ([#circular view](https://github.com/gosling-lang/gosling.js/issues/278#issuecomment-818917482)). Once this is addressed (e.g., having a separate property), we can incorporate it into the responsive design grammar.

**Comment by sehilyi** [comment]
A clarification I want to add is that `responsiveSize` can be defined only at the top level. So, currently, we cannot support defining `responsiveSize` directly on a track (e.g., `"width": {  "ifTrue": 400,   "ifFalse": "vw", ...}`).

**Comment by wangqianwen0418** [comment]
Hi @sehilyi, thanks a lot for these detailed clarifications, which helps me better understand the rationales behind the current grammar.
I am pretty sure that you have thought a lot about the grammar design. Just wish my thoughts (which might be wrong) can be helpful.

The main motivation is to make the grammar more about the function (`conditional spec`) rather than the purpose behind this function (`responsiveness`). So that it is more consistent with how we define the `semantic zoom`. i.e., instead of saying something like "semantic A" & "sematic B", we use conditions to control the visibility of different tracks.
(again, they are just my thoughts and can be flawed)

The two things you mentioned (all conditional spec at one place, multiple conditions) can still be achieved with some modifications.
To put all conditional specs in one place
```
spec: [
   { ifTrue: original_spec, condition: true }, // always true condition
   { ifTrue: spec_1, condition: full_screen_condition },
   { ifTrue: spec_2, condition: tablet_screen_condition },
   { ifTrue: spec_3, condition: phone_screen_condition },
]
```
in this case, the `spec= {...original_spec, ...spec_1 if full_screen_condition, ..spec_2 if tablet_screen_condition, ..spec_3 if phone_screen_condition}`

**Comment by wangqianwen0418** [comment]
> A clarification I want to add is that responsiveSize can be defined only at the top level. So, currently, we cannot support defining responsiveSize directly on a track (e.g., "width": { "ifTrue": 400, "ifFalse": "vw", ...}).

Thanks for the clarification! It makes more sense now. So, is it more like a `responsiveTrigger` rather than an actual size? i.e., the spec & size will changed based on the change of screen width/height?

**Comment by sehilyi** [comment]
Yes, having additional inputs are helpful and highly appreciated!

AFAIU correctly, I think your modified spec becomes now quite identical to what we currently have except for two things, i.e., (1) terms (`spec` vs. `responsiveSpec`) and (2) how you define default specs.

For example, your example spec

```js
spec: [
   { ifTrue: original_spec, condition: true }, // always true condition
   { ifTrue: spec_1, condition: full_screen_condition },
   { ifTrue: spec_2, condition: tablet_screen_condition },
   { ifTrue: spec_3, condition: phone_screen_condition },
]
```

can be slightly changed only by replacing terms with what we currently use

```js
responsiveSpec: [
   { spec: original_spec, selectivity: true }, // always true condition
   { spec: spec_1, selectivity: full_screen_condition },
   { spec: spec_2, selectivity: tablet_screen_condition },
   { spec: spec_3, selectivity: phone_screen_condition },
]
```

In addition, we let users define the default spec outside the `responsiveSpec` property, so bringing the first element outside the array:

```js
...original_spec, // selected by default
responsiveSpec: [
   { spec: spec_1, selectivity: full_screen_condition },
   { spec: spec_2, selectivity: tablet_screen_condition },
   { spec: spec_3, selectivity: phone_screen_condition },
]
```

This allows users that they do not need to make a structural change in a Gosling spec when they want to add responsive designs (i.e., just simply adding `responsiveSpec` from their original spec, so related to viscosity). Also, common properties that can be shared across four specs (i.e., one default and three alternative specs) can be defined only once outside the `responsiveSpec` for conciseness.

```js
...original_spec, // selected by default
..., // <-- any common specs that can be shared across all other alternative specs
responsiveSpec: [
   { spec: spec_1, selectivity: full_screen_condition },
   { spec: spec_2, selectivity: tablet_screen_condition },
   { spec: spec_3, selectivity: phone_screen_condition },
]
```

This structure is similar to how we support semantic zooming in an overlaid track:
```js
alignment: 'overlay',
...original_spec, // used by default
..., // <-- any common specs that can be shared across all other tracks
tracks: [
   { spec: spec_1, visibility: condition_1 },
   { spec: spec_2, visibility: condition_2 },
   { spec: spec_3, visibility: condition_3 },
]
```

This 'structural similarity' was one of the things we considered when trying to make the grammar of responsiveness similar to semantic zooming. The main difference is that the semantic zoom **filters** specs (select multiple specs) by `visibility` conditions while the responsive spec **select** one spec by "selectivity" conditions.

**Comment by sehilyi** [comment]
> The main motivation is to make the grammar more about the function (conditional spec) rather than the purpose behind this function (responsiveness).

I agree with this. The current grammar for responsive designs seems sufficiently generic to me, but probably the terms we currently use are too specific (e.g., `responsiveSpec`). We previously called `alternativeSpec` instead, but we later included "responsive" in the names to make it explicit.

**Comment by wangqianwen0418** [comment]
> I think your modified spec becomes now quite identical to what we currently have

Yes, I see it now. Thanks so much for the clarifications!

**Comment by wangqianwen0418** [comment]
> > The main motivation is to make the grammar more about the function (conditional spec) rather than the purpose behind this function (responsiveness).
> 
> I agree with this. The current grammar for responsive designs seems sufficiently generic to me, but probably the terms we currently use are too specific (e.g., responsiveSpec). We previously called alternativeSpec instead, but we later included "responsive" in the names to make it explicit.

I think the name (`responsiveSpec` or others) mainly depends on whether there are other `selectivity` rather than screen sizes that the users want to use for switching specs.

**Comment by wangqianwen0418** [comment]
> The main difference is that the semantic zoom filters specs (select multiple specs) by visibility conditions while the responsive spec selects one spec by "selectivity" conditions.

Yes, exactly.
I am wondering do you consider unifying `visibility` and `selectivity` as `conditions` in this case?

**Comment by wangqianwen0418** [comment]
> The main difference is that the semantic zoom filters specs (select multiple specs) by visibility conditions while the responsive spec selects one spec by "selectivity" conditions.

Yes, exactly.
I am wondering do you consider unifying `visibility` and `selectivity` as `conditions` in this case?

**Comment by wangqianwen0418** [comment]
> > A clarification I want to add is that responsiveSize can be defined only at the top level. So, currently, we cannot support defining responsiveSize directly on a track (e.g., "width": { "ifTrue": 400, "ifFalse": "vw", ...}).
>
> Thanks for the clarification! It makes more sense now. So, is it more like a `responsiveTrigger` rather than an actual size? i.e., the spec & size will changed based on the change of screen width/height?

Maybe this is a dumb question, will the responsiveSize conflict or duplicate with the `measure` in the condition?
Any thoughts on this?

**Comment by sehilyi** [comment]
> I am wondering do you consider unifying visibility and selectivity as conditions in this case?

I think having different names makes it possible to infer their different actions (control whether to show vs. control whether to select), but other people might have different opinions. Probably, better to get feedback from the group meeting.

> > Thanks for the clarification! It makes more sense now. So, is it more like a responsiveTrigger rather than an actual size? i.e., the spec & size will changed based on the change of screen width/height?
>
> Maybe this is a dumb question, will the responsiveSize conflict or duplicate with the measure in the condition?
Any thoughts on this?

Sorry, I think I missed your question previously. It determines whether to stretch the entire width/height/both of GoslingComponent to fit into its container component (e.g., `<div/>`). When turned on, the actual width and height of the individual track are determined proportionally considering the container width and height. It is a boolean value, so it can be turned on or off (default). [code](https://github.com/gosling-lang/gosling.js/blob/9ca746fd556b88abfef291a48810131da069d763/src/core/gosling.schema.ts#L8) So, `responsiveSize` is a separate thing with `responsiveSpec`.
