### ISSUE TITLE
Comparative matrices example crashes the editor

### ISSUE THREAD

**Issue by manzt** [gosling-lang/gosling.js#673]
Ran into this during BMI 706 today. 

- Chrome: Version 101.0.4951.54 (Official Build) (x86_64)

Steps to reproduce: Navigate to https://gosling.js.org > Coordinated Multiple Views: Comparative Matrices (Micro-C vs. Hi-C)

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/24403730/166523016-25b47c74-3177-4c3a-b48b-af19a2cad4a4.png">

**Comment by sehilyi** [comment]
Found that https://github.com/gosling-lang/gosling.js/pull/663 unintentionally re-assigned a variable that is already used internally in HiGlass tracks, i.e., `gMain`.
