### ISSUE TITLE
color legend and controllers show up in the wrong place

### ISSUE THREAD

**Issue by ngehlenborg** [gosling-lang/gosling.js#685]
In https://gosling.js.org/?example=ALIGNMENT (Gosling.js v0.9.18) the range slider for the color legend shows of in the wrong place and doesn't seem to work (see the two gray rectangles in the conservation and gap views):

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/1216518/167834583-50df5042-f4ef-484f-990f-adf760ca7c5f.png">

**Comment by sehilyi** [comment]
It looks like the legend controller from the default example of the editor (not particularly for this example) is being rendered, and this seems to happen only when specifying an example in the URL (e.g., `https://gosling.js.org/?example=`). I will take a closer look today.

**Comment by ngehlenborg** [comment]
I see. That would make sense. When using the `example` URL parameter, I always see the first example flash up in the preview panel before the example actually loads.
