### ISSUE TITLE
Fail to compile after upgrading gosling.js

### ISSUE THREAD

**Issue by wangqianwen0418** [gosling-lang/gosling.js#735]
The react app fail to compile after upgrading gosling.js from `0.9.0` to `0.9.19`. 
The error info is as below.

```
Failed to compile.

./node_modules/gosling.js/dist/gosling.es.js
Attempted import error: 'generic-filehandle' does not contain a default export (imported as 'require$$7').
```

@sehilyi , any thoughts about what might need to this issue?

**Comment by wangqianwen0418** [comment]
Another issue with the `0.9.19` (not sure whether it is related to the above error) is that the node package does not has a type declaration file

`0.9.19`
![image](https://user-images.githubusercontent.com/19774198/176335083-44eb8651-6baa-4fc6-a70f-1d559902814c.png)

`0.9.18`
![image](https://user-images.githubusercontent.com/19774198/176335226-f5d6b8e3-adbb-407e-a8cd-f0fc5936825b.png)

**Comment by puehringer** [comment]
@wangqianwen0418 The problem appears to be generic-filehandle which changed some ES stuff in the last two versions: https://github.com/GMOD/generic-filehandle/blob/master/CHANGELOG.md#222-2021-12-14

We pinned it to `2.2.1`, in both the dependencies and transitive resolution via 
```
"resolutions": {
    "generic-filehandle": "2.2.1"
}
```

Regarding the typing issue: we also noticed that the `dist/src` folder is missing in `0.9.19`, however it is available in the `0.9.18` version.

**Comment by sehilyi** [comment]
@puehringer Thank you for finding the source of the issue! 

@wangqianwen0418 Thank you for reporting! I can confirm both issues and created a PR to address the first issue. Will try to fix the second issue as soon as possible.

**Comment by wangqianwen0418** [comment]
Thanks @sehilyi and @puehringer !
