### ISSUE TITLE
default `column` and `position` for bigwig data

### ISSUE THREAD

**Issue by manzt** [gosling-lang/gosling.js#768]
Gosling aims in part to provide a consistent tabular data abstraction for genomics data formats. However, for some binary formats this means mapping the binary representation to something columnar. 

For bigwig, the user must explicitly provide explicit names for the `column` and `value`. In Gos, I am considering setting these fields by default to `position` and `value` so that users can avoid repetition.

```python
import gosling as gos

data = gos.bigwig("https://example.com/data.bw")

gos.Track(data).mark_bar().encode(
	x=gos.X("position:G"),
    y=gos.Y("value:Q"),
)
```

Of course this default behavior is something that we can decide in a library like Gos, but it got me thinking about whether it is necessary to allow these fields to be configured in the first place. What if for bigwig, the user always has access to two labeled fields: `position` and `value`. This would mimic the behavior of a csv with named columns. The user doesn't have the ability to name columns of a csv with headers provided, so any bigwig would just be like a csv with the header `position` and `value` always.

**Comment by sehilyi** [comment]
I agree and will make changes to all other relevant data types as well (e.g., vector and multivec).

Since I like the idea of treating bigwig data as columnar data, we can even make those properties (column, value, row, ...) deprecated and could support a generic data transform function:

```ts
dataTransform: [{
  type: 'rename', mapping: [
    { from: "position", to: "pos" },
    { from: "value", to: "count" }, 
    ...
}]
```
