### ISSUE TITLE
Circos example seems to be broken?

### ISSUE THREAD

**Issue by sehilyi** [gosling-lang/gosling.js#771]
![Screen Shot 2022-07-18 at 15 22 44](https://user-images.githubusercontent.com/9922882/179600970-b5f2c551-df71-4492-a6b9-653877d48634.png)
https://gosling.js.org/?example=CIRCOS

**Comment by manzt** [comment]
seems to be working for me: 

<img width="816" alt="image" src="https://user-images.githubusercontent.com/24403730/179622775-40df3771-9b62-4050-b8ef-6584a8c4b9de.png">

```
  System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 7.98 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Browsers:
    Chrome: 103.0.5060.114
    Firefox Nightly: 104.0a1
    Safari: 15.4
```

**Comment by sehilyi** [comment]
Oh, forgot to close this in https://github.com/gosling-lang/gosling.js/pull/772.
