### ISSUE TITLE
`GenomicDomain` doesn't support custom chromsizes

### ISSUE THREAD

**Issue by manzt** [gosling-lang/gosling.js#793]
The `Chromosome` type is hard-coded with human genome name literals (e.g. "chr1", "1", ...). In Gos, this causes an issue where you cannot initialize the domain for the visualization for the named chromosomes:

```python
gos.overlay(...).properties(
   assembly=[["NC_045512.2", 29903]],
   xDomain=gos.GenomicDomain(chromosome="NC_045512.2", interval=[1, 29903]),
 )
# Error!!! chromsome not one of "chr1" ... 
```

Chromosome should just be a `string`. I think we should try to avoid any magic with coercing chromosome names (e.g., (`name.replace("chr", "")`) since this gets quite complicated. Although as mentioned in #709, perhaps some fuzzy-ness is useful? In that case I would be extremely explicit about how coercion works and have a utility which does this (and can be tested carefully). i.e.,

```typescript
// returns valid key of assembly _or_ throws
function coerceChromIdentifier<
  Sizes extends Record<string, number>
>(name: string, sizes: Sizes): keyof Sizes {
  // exact match
  if (name in sizes) return name;
  
  let test;
  // strip chr prefix
  test = name.slice("chr".length)
  if (test in sizes) return test;

  // append chr prefix
  test = "chr" + name;
  if (test in sizes) return test;

  throw new Error("invalid identifier, could not be coerced");
}
```

**Comment by sehilyi** [comment]
Ah, will update this shortly. 

Given that there is only one chromosome in the custom assembly, I think you can remove the `chromosome` field as a workaround.

```python
gos.overlay(...).properties(
   assembly=[["NC_045512.2", 29903]],
   xDomain=gos.GenomicDomain(interval=[1, 29903]),
)
```

**Comment by manzt** [comment]
Thanks for the quick reply! I've done this in the documentation: just thinking about future support! https://gosling-lang.github.io/gos/gallery/covid.html

**Comment by sehilyi** [comment]
I think fuzzy-ness can be useful when datasets for the same assembly use varying chromosome prefixes (e.g., `1`, `chr1`, and `hs1`). I think we could either support the fuzzy-ness (e.g., convert `1` and `hs` to `chr1` when fetching new tiles?) or just let users explicitly specify the prefix under the "data" property, something like:

```ts
{
  assembly: 'hg39',
  tracks: [
    { ..., "data": {
      "url": "https://raw.githubusercontent.com/vigsterkr/circos/master/data/5/segdup.txt",
      "type": "csv",
      "headerNames": ["id", "chr", "p1", "p2"],
      "chromosomePrefix": "hs", // e.g., "hs1", "hs2", etc are converted to "chr1", "chr2", etc
      ...
    }}, 
    ...
  ],
  xDomain: { chromosome: "chr1" }, // use the `chr` prefix as usual
}
```
