### ISSUE TITLE
the y-axis is improperly flipped

### ISSUE THREAD

**Issue by wangqianwen0418** [gosling-lang/gosling.js#856]
![image](https://user-images.githubusercontent.com/19774198/228846187-f787d58b-edfd-4387-ae4f-4b12bc16158b.png)

**Comment by sehilyi** [comment]
HiGlass rotates the canvas to make a vertical track. We will need to flip the axis ourselves again to make it readable. In the axis rendering function (https://github.com/gosling-lang/gosling.js/blob/c1e55ec4562cf138079366eb17b956480266c581/src/core/mark/axis.ts#LL17), we can add an additional case that flips the y-axis if the `orientation` is `vertical`.

A similar issue in HiGlass:

- https://github.com/higlass/higlass/issues/1006

**Comment by etowahadams** [comment]
To reproduce: 
```
{
  "orientation":"vertical",
  "tracks": [
              {
                "id": "1-1",
                "title": "Sample 1",
                "data": {
                  "url": "https://resgen.io/api/v1/tileset_info/?d=Zz3CBDSqQ3ySrOSe2yj1eg",
                  "type": "vector",
                  "column": "position",
                  "value": "peak",
                  "binSize": 4
                },
                "mark": "bar",
                "x": {
                  "field": "start",
                  "type": "genomic",
                  "axis":"bottom",
                  "linkingId": "1"
                },
                "xe": {"field": "end", "type": "genomic"},
                "y": {
                  "field": "peak",
                  "type": "quantitative",
                  "axis":"left",
                  "flip": false
                },
                "color": {"value": "#CC7DAA"},
                "stroke": {"value": "white"},
                "strokeWidth": {"value": 0.2},
                "style": {"background": "lightgray", "backgroundOpacity": 0},
                "width": 700,
                "height": 400
              }
            ]
}

```
Orientation horizontal:
<img width="761" alt="image" src="https://user-images.githubusercontent.com/14843470/229570043-129d9075-2157-427f-91b4-4f9539a0d68a.png">
Orientation vertical:
<img width="771" alt="image" src="https://user-images.githubusercontent.com/14843470/229570151-fc0d1615-0eb9-4ebe-b06c-17d21070c93c.png">
