### ISSUE TITLE
plotly like multiple sequence alignment chart (in the examples) does not render the alignment

### ISSUE THREAD

**Issue by andreassteffen** [gosling-lang/gosling.js#886]
https://gosling.js.org/?example=SEMANTIC_ZOOM
this is what it looks like at the moment:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/1114010/236126297-406b602a-5a15-4a19-afd0-cb5093644b92.png">

**Comment by sehilyi** [comment]
Hi @andreassteffen, thanks a lot for creating this issue! I addressed this in [this PR](https://github.com/gosling-lang/gosling.js/pull/892) and will be fixed in the next release.
