### ISSUE TITLE
Support triangle mark with start and end

### ISSUE THREAD

**Issue by ThHarbig** [gosling-lang/gosling.js#904]
I think it would be useful to support triangle shapes with a start and end point (similar to rect) like in this example [(created with GeneSpy and iTol):](https://doi.org/10.1093/bioinformatics/bty459)
<img width="378" alt="image" src="https://github.com/gosling-lang/gosling.js/assets/15909854/e94a4d72-32c4-4528-a7e7-982bb25e1141">
This could either be done (1.) using a shape (#241) or (2.) by extending the current implementation of triangle (`x` and `xe`) or (3.) creating a new mark. I don't know what it would be called though.

**Comment by sehilyi** [comment]
Oh, actually, it is possible to encode the varying width of triangles using `x` and `xe`.

<img width="384" alt="Screenshot 2023-05-18 at 15 31 11" src="https://github.com/gosling-lang/gosling.js/assets/9922882/c4043002-dbf0-488d-9086-5df1601e5ef0">

<a href="https://gosling.js.org/?full=false&spec=(Q'layoutB'linear'%2CQ'xDomain~chromosomeB'chr3'CintervalK52168000%2C%2052890000%5D)%2CQ%26horizontal'%2CQ'viewsKQ*(Q**%26vertical'%2CQ**'viewsKQ***(4'alignmentB'overlay'E'titleB'HiGlass'E'dataB(4*'urlB'https%3A%2F%2Fserver.gosling-lang.org%2Fapi%2Fv1%2Ftileset_info%2F%3Fd%3Dgene-annotation'E*'Mbeddb'E*'genomic%251%5E2%3EE*'value%255VXCY)EN3Vname'CY)4*%5DE*'exonInterval%2512%5E13%3E4)E'tracksK4qJjJX%3B%2BZleRigh%40%3C)Uxe~Send%3C%244*)EqJjJX%3B-ZleLef%40W)Uxe~SendW%24Ustyle~alignB'right')4*)4%5DE'row~SXCYC%22)E'colorB(4*'SXE*'YE*'%22E*'rangeK'%237585FF'C%23FF8A85'%5D4)E'visibilityK4*(4**'operationB'less-than'UmeasureB'width'UthresholdB'%7Cxe-x%7C'UtransitionPaddingB10UtargetB'mark'4*)4%5DE'opacity~valueB0.8)E'widthB350E'heightB100Q***)Q**%5DQ*)Q%5D%0A)*%20%204Q****B!%20C%2C%20'E%2C4J***('Mfilter'CSKB%5BMtypeB'N**('indexBQ%0A*SfieldB'UE**'VCnameB'W'CMgenomic'Xstrand'YMnominal'Z'%5D)4**%5DUmarkB'triangjtype'%3Bgene'%5D)Eq*(4**'dataTransformK4~B('%22domainK'%2B'C-'%5D%24)Usize~valueB15)%25FieldsK4N%26'arrangementB'%3BConeOfK'%3CWCaxisB'top'%3EVend')4*%5D%40t'Ux~Sstart%5EVstart')EN%01%5E%40%3E%3C%3B%26%25%24%22~qjZYXWVUSQNMKJECB4*_">demo</a>

**Comment by ThHarbig** [comment]
Perfect, thank you!
