### ISSUE TITLE
Default padding for barcharts

### ISSUE THREAD

**Issue by austin-mbs** [gosling-lang/gosling.js#907]
Looking at this example:
https://gosling.js.org/?example=doc_bar
Is there a way to add domain padding without knowing the min/max values and adding it manually? Currently, I haven't been able to locate a built-in way to do this.

For example, adding a 20% space buffer to the top of a chart for presentational purposes.

**Comment by sehilyi** [comment]
Hi, @austin-mbs!

You can achieve it by setting a `range` smaller than your track's `height'.

```diff
{
  "title": "Basic Marks: bar",
  "subtitle": "Tutorial Examples",
  "tracks": [
    {
      "layout": "linear",
      "width": 800,
      "height": 180,
      "data": {
        "url": "https://resgen.io/api/v1/tileset_info/?d=UvVPeLHuRDiYA3qwFlm7xQ",
        "type": "multivec",
        "row": "sample",
        "column": "position",
        "value": "peak",
        "categories": ["sample 1"],
        "binSize": 5
      },
      "mark": "bar",
      "x": {"field": "start", "type": "genomic", "axis": "bottom"},
      "xe": {"field": "end", "type": "genomic"},
-      "y": {"field": "peak", "type": "quantitative", "axis": "right" },
+      "y": {"field": "peak", "type": "quantitative", "axis": "right", "range": [0, 144]},
      "size": {"value": 5}
    }
  ]
}
```

<a href="https://gosling.js.org/?full=false&spec=(6'XtleGBasic%20Marks%3A%20barjsubXtleGTutorial%20ExNsjtracksZ6*(K'layoutGlinear'Wwidth2800Wheight2180Wdata~K*'urlGhttps%3A%2F%2Fresgen.io%2Fapi%2Fv1%2FXleset_info%2F%3Fd%3DUvVPeLHuRDiYA3qwFlm7xQ9OmulXvec9rowGsN9columnGposiXon9valueGpeak9categoriesZ'sN%201'%5D-*'binSize25K)WmarkGbar'Wx~IstartCJ'axisGbottom')Wxe~IendC)Wy~K*Ipeak9OquanXtaXve9axisGright9rangeZ0J144%5DK)Wsize~'value25)6*)6%5D%0A)*%20%20-%2CK2!%206%0A*9'-*'C'J'Ogenomic'G2'I'fieldGJ%2C%20K6**NampleOtypeGW-'XtiZ2%5Bj'%2C6'~2(%01~jZXWONKJIGC962-*_">JS Editor Demo</a>

## Before
![gosling-visualization (11)](https://github.com/gosling-lang/gosling.js/assets/9922882/2149d205-61fa-4bfd-8745-731229008ad8)


## After
![gosling-visualization (13)](https://github.com/gosling-lang/gosling.js/assets/9922882/616f12b3-4d8d-4426-a59b-8646f0c90ce4)

**Comment by austin-mbs** [comment]
Thank you!
