### ISSUE TITLE
randomly missing Rect after zooming

### ISSUE THREAD

**Issue by cschin** [gosling-lang/gosling.js#916]
I have a use case that I like to see all rows in a track.  However, I found that he Goling.js was not able to render some Rect after zooming and it is random. (See the attached the two panels have the same input data in JSON  without higlass server

<img width="845" alt="image" src="https://github.com/gosling-lang/gosling.js/assets/1320747/2378cdf8-c47e-4825-893c-99aa6f1edd4c">
)

I did some experiments and traced the code a bit. I think the PIXI.js may not render it correctly due to delays for processing the data. If I reduced the number of the Rect to be rendered, it seemed doing ok.  I tried to tweak the "forceDraw()" call to ensure all Rect are render, no luck so far.  Is there a way to enforce all Rect rendering reliably after zooming?

**Comment by sehilyi** [comment]
Hi @cschin! Thank you for making a GH issue!

Have you tried `sampleLength`, which can be found at http://gosling-lang.org/docs/data#json-no-higlass-server

When there are many data items, Gosling (randomly) selects a subset of data by default (i.e., `1000`). You can try increasing it.

Also, using a separate CSV file will be much faster than an inlined JSON value if you confront performance issues.

**Comment by cschin** [comment]
@sehilyi thanks a lot. in my case, I have to set it a large number... but it does work. Great work on Gosling!!

You might consider this before. Bokeh uses a strategy downsampling during zoom / pan, but full rendering at the end.  In my case, I can't afford missing data to be perceived as gaps, the rendering speed is the 2nd consideration.
