### ISSUE TITLE
Help with online editor for other species

### ISSUE THREAD

**Issue by annerilotter** [gosling-lang/gosling.js#921]
### Discussed in https://github.com/gosling-lang/gosling.js/discussions/919

<div type='discussions-op-text'>

<sup>Originally posted by **annerilotter** June 19, 2023</sup>
Hi

I love this project and the visualizations that can be created with it.

I wanted to ask if you could provide some guidance to generate a 'plain' circos for a non-reference organism using the online editor (I understand that you may not support this at the moment, but I would love if you could). I am struggling to understand how to set up the input data to generate a circus with just the chromosomes represented. What I have is as following: 

Chromosome,chromStart,chromEnd,Name
Chr01,0,44965197,Chr01
Chr02,0,59529170,Chr02
Chr03,0,83952244,Chr03
Chr04,0,41160059,Chr04
Chr05,0,76243064,Chr05
Chr06,0,57472304,Chr06
Chr07,0,54830020,Chr07
Chr08,0,72515979,Chr08
Chr09,0,39307835,Chr09
Chr10,0,37777128,Chr10
Chr11,0,44836791,Chr11

When I use the URL for this data, the image does not render the new data as input. Am I maybe missing something?

Kind regards</div>

**Comment by sehilyi** [comment]
Please refer to my response in your original post!

https://github.com/gosling-lang/gosling.js/discussions/919#discussioncomment-6244017
