### ISSUE TITLE
Dummy/placeholder track/view

### ISSUE THREAD

**Issue by ThHarbig** [gosling-lang/gosling.js#924]
At the moment it is not (easily) possible to place other non-gosling-related views in-between gosling views. A use case for this would be placing metadata views or views with alt texts next to gosling views.

One idea I had is having a placeholder view/track that can be accessed using an ID

**Comment by sehilyi** [comment]
We can add an additional track type [here](https://github.com/gosling-lang/gosling.js/blob/afcf002654ee59fdbcada474458eacd56d264f71/src/core/gosling.schema.ts#L155), e.g., `DummyTrack`. The usage could be like:

```ts
{
   views: [
     {  tracks: [{type: 'dummy'}] }
  ]
}
```

**Comment by sehilyi** [comment]
Some properties that need to be included:

- `id`: To use JS APIs (e.g., `ref.current.api.getTrack('placeholder-1')`)
- `style`: Mainly to determine how to style the dummy track (e.g., background and border we currently use in other tracks)
- `height` and `width`: Determines the size of the track
- `label` (or more intuitive name): for showing a text label for a placeholder
