### ISSUE TITLE
Idea: add IDs to views

### ISSUE THREAD

**Issue by ThHarbig** [gosling-lang/gosling.js#929]
Currently, only tracks have IDs, but I think it might be helpful to associate views with ID, for example, to get a view by its ID and retrieve its height.

**Comment by sehilyi** [comment]
support view IDs and then add API for views (refer to APIs for tracks).

**Comment by sehilyi** [comment]
We can support assigning IDs to views at any level. A view with a certain ID can contain multiple child views:

```ts
{
   id: 'root-view',
   views: [
      { id: 'view-1', views: [...] },
      { id: 'view-2', tracks: [{..., id: 'track-1' }, ...] },
   ]
}
```

Useful APIs to support:

- get the bounding boxes of a view
- get the spec of a view
