### ISSUE TITLE
BED datafetcher works locally but not when deployed 

### ISSUE THREAD

**Issue by etowahadams** [gosling-lang/gosling.js#936]
BED datafetcher is not working properly because tabix-js isn't using explicit Buffer imports. I just submitted a [PR](https://github.com/GMOD/tabix-js/pull/140) to tabix-js. So hopefully its resolved soon. 

I happened to look at the [deployed BED data fetcher](https://gosling.js.org/?example=doc_bed) and noticed it wasn't working properly. The data does not load and the following error shows up in the console: 
<img width="503" alt="image" src="https://github.com/gosling-lang/gosling.js/assets/14843470/5ee97b2f-8243-476b-a306-3e1818e6fa51">

However, everything seems to work fine when I test things locally. 

I believe this is the same issue that was encountered before with [Buffer needing to be polyfilled](https://github.com/GMOD/generic-filehandle/pull/102), thus necessitating to explicit Buffer imports.

**Comment by sehilyi** [comment]
As a debugging tip, you can test the deployment version using `yarn preview` after `yarn build` and `yarn build-editor`:

https://github.com/gosling-lang/gosling.js/blob/master/CONTRIBUTING.md#testing-production-build-using-editor
