### ISSUE TITLE
Broken tracks from viewID support

### ISSUE THREAD

**Issue by etowahadams** [gosling-lang/gosling.js#953]
The commit https://github.com/gosling-lang/gosling.js/commit/cd8d3000f7e1e86422ec89f765585f6056d64a9f from https://github.com/gosling-lang/gosling.js/pull/939 which adds IDs to views broke several visualizations. It only affected certain visualizations which is why we didn't catch it at the time. 

Example: Band connection:

Before commit:
<img width="200" alt="image" src="https://github.com/gosling-lang/gosling.js/assets/14843470/3e0c39fa-af08-464f-94ea-c760e1a54736">
After: 
<img width="200" alt="image" src="https://github.com/gosling-lang/gosling.js/assets/14843470/95111d8d-599e-4232-beff-2bf1a055e2b4">

Example: Hi-C matrix with annotations 
Before commit
<img width="200" alt="image" src="https://github.com/gosling-lang/gosling.js/assets/14843470/49a7c977-3b81-496d-b9b8-757d124cbcc9">
After 
<img width="200" alt="image" src="https://github.com/gosling-lang/gosling.js/assets/14843470/64ae8e13-a8cf-4f45-8458-f5d5ae503670">

cc: @sehilyi

**Comment by sehilyi** [comment]
Thanks a lot for finding this, @etowahadams !
