### ISSUE TITLE
Support for using data from authenticated URLs 

### ISSUE THREAD

**Issue by etowahadams** [gosling-lang/gosling.js#963]
We would like Gosling to be able to use data from private URLs. To do this, we need add a new option to the Gosling schema. 

**Background and motivation**
Currently, users provide Gosling with a URL to their data. Data fetchers get the data from the URL. However, if the URL points to a server which requires certain request options, for example a HTTP Authorization request header, then Gosling will not be able to retrieve that data. 

One use case is retrieving files private files from Google Drive. To retrieve private files from Google drive, web applications must obtain an OAuth 2.0 authorization token. The web application can then [send that authorization token](https://developers.google.com/identity/protocols/oauth2#4.-send-the-access-token-to-an-api.) to a Google API to do things which are permitted by the authorization token's scope. 

**Proposed Gosling Schema changes**
I propose adding a an optional property called `fetchOptions` to each data type that takes a URL (csv, gff, vcf, etc. but not json). The `fetchOptions` property will take an object which has the [RequestInit](https://fetch.spec.whatwg.org/#requestinit) type.  Alternatively, it could take a more limited version of this type. 

```
interface RequestInit {
    /** A BodyInit object or null to set request's body. */
    body?: BodyInit | null;
    /** A string indicating how the request will interact with the browser's cache to set request's cache. */
    cache?: RequestCache;
    /** A string indicating whether credentials will be sent with the request always, never, or only when sent to a same-origin URL. Sets request's credentials. */
    credentials?: RequestCredentials;
    /** A Headers object, an object literal, or an array of two-item arrays to set request's headers. */
    headers?: HeadersInit;
    /** A cryptographic hash of the resource to be fetched by request. Sets request's integrity. */
    integrity?: string;
    /** A boolean to set request's keepalive. */
    keepalive?: boolean;
    /** A string to set request's method. */
    method?: string;
    /** A string to indicate whether the request will use CORS, or will be restricted to same-origin URLs. Sets request's mode. */
    mode?: RequestMode;
    /** A string indicating whether request follows redirects, results in an error upon encountering a redirect, or returns the redirect (in an opaque fashion). Sets request's redirect. */
    redirect?: RequestRedirect;
    /** A string whose value is a same-origin URL, "about:client", or the empty string, to set request's referrer. */
    referrer?: string;
    /** A referrer policy to set request's referrerPolicy. */
    referrerPolicy?: ReferrerPolicy;
    /** An AbortSignal to set request's signal. */
    signal?: AbortSignal | null;
    /** Can only be null. Used to disassociate request from any Window. */
    window?: null;
}
``` 
**Example usage**
Getting a file with an authorization header 
```
data: {
    url: 'https://<google drive url>.csv',
    type: 'csv',
    fetchOptions: {'headers': {'Authorization': 'Bearer [YOUR_ACCESS_TOKEN]'}}
    chromosomeField: 'Chromosome',
    genomicFields: ['chromStart', 'chromEnd']
},
```

cc: @sehilyi @manzt

**Comment by manzt** [comment]
Love this idea! Think it's an excellent use case but am hesitant to extend the spec to add this feature for several reasons:

1. Coupling spec to a specific Web API. Right now Gosling runs in the browser and it's datafetchers are built on the `fetch` API. Adding `fetchOptions` to the spec exposes this implementation detail to end users (a leaky abstraction). If we were to ever change the implementation (not likely, but in theory possible) then we'd need to port this options to the new HTTP client. If there were ever a renderer for Gosling that was designed to run outside the browser, which in theory is possible for a declarative framework/grammar, then this would also be an issue.

2. Repeated configuration in ever data entry. Not specific to `fetchOptions`, but it can already be tedious to repeat `data` in the spec and these options almost certainly do not change between tracks.

3. Ephemeral `fetchOptions`. Auth headers/tokens often don't persist and we would be embedding them into the spec. This means the spec itself must be updated for potentially the same URL. Also we could introduce an issue where folks accidently check-in things like API keys to version control if they are saving their spec.

As an alternative, I wonder about exposing an option on the _renderer_ (which is specific to gosling.js) to support this kind of feature.

```js
gosling.embed(spec, el, {
  fetchOptions: {
    "https://example.com/data.bam": {
      headers: { Authorization: "XXX" }
    }
  } 
})
```

**Comment by manzt** [comment]
also noting that index files are configured in the same data entry but have a separate URL and will likely have separate HTTP headers.

**Comment by etowahadams** [comment]
I agree with these points! I see how my proposed implementation is a leaky abstraction. And that it doesn't make sense to save temporary tokens in the schema. 

To implement 
```js
gosling.embed(spec, el, {
  fetchOptions: {
    "https://example.com/data.bam": {
      headers: { Authorization: "XXX" }
    }
  } 
})
```
there needs to be a way to tell the datafetchers to use those `fetchOptions` when they `fetch`. Unfortunately Gosling datafetchers only communicate with Gosling through HiGlass and they receive the following parameters from HiGlass:  

https://github.com/higlass/higlass/blob/b2ee5940c519982dc53685153ff863d64443d0bb/app/scripts/plugins/get-data-fetcher.js#L19-L23
 ```js
return new pluginDataFetcher.dataFetcher(
      availableForPlugins,
      dataConfig,
      pubSub,
    );
```
Assuming we don't want to change HiGlass, I can think think of a few solutions. 

1. Patch `window.fetch` when `gosling.embed` is called so that when `fetch` is used elsewhere in Gosling it will use the appropriate `fetchOptions`. In general I know it is frowned upon to patch Web APIs so this would not be ideal. 
```js
const { fetch: originalFetch } = window;

window.fetch = async (...args) => {
    let [resource, config] = args;
    if (resource in fetchOptions) {
         // update config 
    }
    const response = await originalFetch(resource, config);
    return response;
};
```
2. Have `gosling.embed` save the `fetchOptions` to `sessionStorage`, and have `RemoteFile.read` check `sessionStorage` for fetch options. In this case it would probably be better for all of the datafetchers to be using `RemoteFile`. 

I wish there were a better way to pass this information around but I can only think of using `sessionStorage` at the moment so that is what I'm inclined to do. Would love to hear any thoughts!

**Comment by sehilyi** [comment]
In order to pass on the additional information, you can extend the `DataConfig` type of data fetchers, just like how we add `assembly` information to data fetchers (refer to `CommonDataConfig`). `assembly` is not part of the original data config in Gosling.js spec, but we pass that information to calculate the absolute genomic positions.

https://github.com/gosling-lang/gosling.js/blob/9b36b6c473c9707907c4cc86a8df7a07b150b1be/src/data-fetchers/csv/csv-data-fetcher.ts#L8

https://github.com/gosling-lang/gosling.js/blob/9b36b6c473c9707907c4cc86a8df7a07b150b1be/src/data-fetchers/utils.ts#L7-L8

https://github.com/gosling-lang/gosling.js/blob/9b36b6c473c9707907c4cc86a8df7a07b150b1be/src/compiler/gosling-to-higlass.ts#L156-L160

**Comment by etowahadams** [comment]
Ah I see how this would allow something in a Gosling spec to be accessible to a datafetcher, thanks! 

So one possibility could be to pass `fetchOptions` to the compiler, and have the compiler add the `fetchOptions` to the HiGlass spec. And the HiGlass schema would have to also expand. 

https://github.com/gosling-lang/gosling.js/blob/9b36b6c473c9707907c4cc86a8df7a07b150b1be/src/higlass-schema/higlass.schema.ts#L103-L116

This sounds like a reasonable strategy to me. I don't like that the HiGlass schema has to be changed, but I guess this Data interface is meant to be flexible?

**Comment by sehilyi** [comment]
Yes, the idea was that when we have actual HiGlass types, we can extend them in Gosling.js so that additional properties that are needed in Gosling.js can be included. We can extend higlass' `Data` in Gosling.js in a more polished way though, i.e., not directly editing the `higlass.schema.ts`.
