### ISSUE TITLE
Genomic axis hides chr<N> labels

### ISSUE THREAD

**Issue by puehringer** [gosling-lang/gosling.js#990]
When looking at the whole genome, it would be great if the chr<N> would not randomly disappear. I know that it checks if there is enough space to show the labels, but the threshold should be configurable. 

In the example at https://gosling.js.org/?example=doc_bar, it randomly hides chr5, chr6, ...: 

![image](https://github.com/gosling-lang/gosling.js/assets/51900829/085fda4f-816f-4622-a9d7-62b299324f37)

As an alternative, is there a way to change to just <N> when zoomed out?

**Comment by ngehlenborg** [comment]
@puehringer I'm not 100% sure, but I believe that there might be a prioritization function somewhere that determines which labels get dropped first (at least that how it is done in the gene annotation track in HiGlass). @sehilyi Can probably comment on how the Gosling genomic axis is implemented and if there is a way to change how and when labels etc. are dropped.

**Comment by ngehlenborg** [comment]
@puehringer I'm not 100% sure, but I believe that there might be a prioritization function somewhere that determines which labels get dropped first (at least that how it is done in the gene annotation track in HiGlass). @sehilyi Can probably comment on how the Gosling genomic axis is implemented and if there is a way to change how and when labels etc. are dropped.

**Comment by sehilyi** [comment]
Hi @puehringer! The current logic is that if labels overlap each other, one of the labels is hidden randomly:

https://github.com/gosling-lang/gosling.js/blob/108d49634e6fa3e3feead372904525db61b45715/src/tracks/gosling-genomic-axis/axis-track.ts#L672-L686

A hard-coded `5px` margin is used when calculating collisions. I think Gosling can expose this as a user option, e.g., `axisLabelMargin: 0` for no margin, `axisLabelMargin: -1` for not hiding labels at all.

These are some possible examples:

## Zero margins (`axisLabelMargin: 0`)

![Screenshot 2023-11-15 at 12 38 36](https://github.com/gosling-lang/gosling.js/assets/9922882/768510f8-0f88-4167-a0ec-2222b3e8842f)

## No hiding (`axisLabelMargin: -1`)

![Screenshot 2023-11-15 at 12 38 14](https://github.com/gosling-lang/gosling.js/assets/9922882/018002fa-bd3d-469b-8d1c-b0bd131936b2)

**Comment by puehringer** [comment]
Hi @sehilyi, this looks close to what we are looking for! Any change we can have an option to simply show the labels without the "chr"? That way, the "No hiding (axisLabelMargin: -1)" case would have plenty of space to show all chromosomes.

**Comment by sehilyi** [comment]
Hi @puehringer, could you take a look at https://github.com/gosling-lang/gosling.js/pull/996 to see whether it would support your use case? I added two options as part of the Gosling theme, so the usage would be `<GoslingComponent spec={spec} theme={{ base: 'light', axis: { labelMargin: -1, excludeLabelChrPrefix: true } }}/>`.

**Comment by dvmoritzschoefl** [comment]
> Hi @puehringer, could you take a look at #996 to see whether it would support your use case? I added two options as part of the Gosling theme, so the usage would be `<GoslingComponent spec={spec} theme={{ base: 'light', axis: { labelMargin: -1, excludeLabelChrPrefix: true } }}/>`.

@sehilyi I tested these 2 options for our use case and this is exactly what we need.
