### ISSUE TITLE
Increase minimum HiGlass peerdependency version 

### ISSUE THREAD

**Issue by etowahadams** [gosling-lang/gosling.js#999]
[Higlass 1.13.3](https://github.com/higlass/higlass/releases/tag/v1.13.3) injects CSS directly into the final HiGlass build, obviating the need a external stylesheet (for example `<link rel="stylesheet" href="https://esm.sh/higlass@1.13/dist/hglib.css">`). 

We could increase the minimum HiGlass version that Gosling uses to be `^=1.13.3` and not require users to add the HiGlass stylesheet. This would would mainly result in a change in the Gosling [usage documentation](http://gosling-lang.org/docs/usage). Does this sound reasonable? @manzt @sehilyi

**Comment by sehilyi** [comment]
Sounds good to me! Manually importing CSS was error-prone and annoying in some cases.
